version: "3"

services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app
      - ./logs/backend:/logs

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/app
    environment:
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"
